<?php

// $Id$

/**
 * @file
 *
 */

/**
 *
 * @param array $form_state
 * @param string $form_name 
 * 
 * @return array
 */
function xml_form_builder_edit(array &$form_state, $form_name) {
  
}

/**
 *
 * @param array $form
 * @param array $form_state 
 */
function xml_form_builder_validate(array $form, array &$form_state) {
  
}

/**
 *
 * @param array $form
 * @param array $form_state 
 */
function xml_form_builder_submit(array $form, array &$form_state) {
  
}