<?php

// $Id$

/**
 * @file
 *
 */
module_load_include('inc', 'xml_form_api', 'Form');

/**
 * Implementation of Hook Menu.
 *
 * @return array
 */
function xml_form_api_menu() {
  $items['FormDefinition.xsd'] = array(
    'title' => 'Form Definition',
    'description' => 'Returns FormDefinition.xsd',
    'page callback' => 'xml_form_api_get_form_defintion',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['test'] = array(
    'title' => 'Test',
    'description' => 'test',
    'page callback' => 'xml_form_api_test',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Menu Callback, returns FormDefinition.xsd
 */
function xml_form_api_get_form_defintion() {
  
}

function createTestDefinition() {
  $document = new DOMDocument();
  $document->load(drupal_get_path('module', 'xml_form_api') . '/FormDefinition.xml');
  $xml = $document->saveXML();
  return FormDefinition::createFromXMLDefiniton($xml);
}

function createTestDocument($document_properties) {
  $document = new DOMDocument();
  $document->load(drupal_get_path('module', 'xml_form_api') . '/test_data/mods.xml');
  $xml = $document->saveXML();
  return new Document($document_properties, $xml);
}

/**
 * 
 */
function xml_form_api_test() {
  return drupal_get_form('xml_form');
}

function xml_form(&$form_state) {
  $form = new Form($form_state);
  if (!$form->isInitialized()) { // Was initialized from storage.
    // Create Definition.
    $definition = createTestDefinition();
    // Create Document.
    $properties = $definition->properties;
    $document_properties = $properties->document;
    $document = createTestDocument($document_properties);
    // Intialize form.
    $form->initialize($definition, $document); // Hidden Params for extra, but at very least we need the definition.
  }
  return $form->toDrupalForm();
}

function xml_form_validate($form, &$form_state) {
  //$form = new Form($form_state);
  //$form->validate($form_state);
}

function xml_form_submit($form, &$form_state) {
//  Requires some check to make sure its not a ahah callback...
//  $form = new Form($form_state);
//  $document = $form->submit($form_state);
//  Utils::prettyPrintDocument($document);
//  exit();
}
