<?php

// $Id$

/**
 * @file
 *
 */
module_load_include('inc', 'xml_form_builder', 'Edit'); // Needed to make use of AHAH functions...
module_load_include('inc', 'xml_form_builder', 'Preview'); // Needed to make use of AHAH functions...

/**
 * Implements hook_menu. Register menus.
 *
 * @return array 
 */
function xml_form_builder_menu() {
  module_load_include('inc', 'xml_form_builder', 'FormBuilder');
  /**
   * Inital page. Lists the existing forms showing a preview of each. The user is provided with links for 
   * creating, editing, deleting, or copying forms.
   */
  $items['admin/content/xml/form'] = array(
    'title' => 'XML Form Builder',
    'description' => 'Manage XML Based Forms.',
    'file' => 'List.inc',
    'file path' => drupal_get_path('module', 'xml_form_builder'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('xml_form_builder_list'),
    'access arguments' => array(FormBuilder::PERM_LIST_FORMS),
    'type' => MENU_NORMAL_ITEM,
  );
  /**
   * View a form.
   */
  $items['admin/content/xml/form/%/view'] = array(
    'title' => 'Preview Form',
    'description' => 'Preview a form.',
    'file' => 'Preview.inc',
    'file path' => drupal_get_path('module', 'xml_form_builder'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('xml_form_builder_preview', 4),
    'access arguments' => array(FormBuilder::PERM_LIST_FORMS),
    'type' => MENU_CALLBACK,
  );
  /**
   * Export the form.
   */
  $items['admin/content/xml/form/%/export'] = array(
    'title' => 'Export Form',
    'description' => 'Export a form.',
    'page callback' => 'xml_form_builder_export',
    'page arguments' => array(4),
    'access arguments' => array(FormBuilder::PERM_LIST_FORMS),
    'type' => MENU_CALLBACK,
  );
  /**
   * Presents a form that allows the user to create a new form.
   */
  $items['admin/content/xml/form/create'] = array(
    'title' => 'Create Form',
    'description' => 'Create a new Form.',
    'file' => 'Create.inc',
    'file path' => drupal_get_path('module', 'xml_form_builder'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('xml_form_builder_create'),
    'access arguments' => array(FormBuilder::PERM_CREATE_FORMS),
    'type' => MENU_CALLBACK,
  );
  $items['admin/content/xml/form/%/copy'] = array(
    'title' => 'Copy Form',
    'description' => 'Copy an existing Form.',
    'file' => 'Copy.inc',
    'file path' => drupal_get_path('module', 'xml_form_builder'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('xml_form_builder_copy', 4),
    'access arguments' => array(FormBuilder::PERM_CREATE_FORMS),
    'type' => MENU_CALLBACK,
  );
  $items['admin/content/xml/form/%/edit'] = array(
    'title' => 'Edit Form',
    'description' => 'Edit a Form.',
    'file' => 'Edit.inc',
    'file path' => drupal_get_path('module', 'xml_form_builder'),
    'page callback' => 'xml_form_builder_edit',
    'page arguments' => array(4),
    'access arguments' => array(FormBuilder::PERM_EDIT_FORMS),
    'type' => MENU_CALLBACK,
  );
  $items['admin/content/xml/form/%/edit/save'] = array(
    'title' => 'Edit Form',
    'description' => 'Edit a Form.',
    'file' => 'Edit.inc',
    'file path' => drupal_get_path('module', 'xml_form_builder'),
    'page callback' => 'xml_form_builder_edit_save',
    'page arguments' => array(4),
    'access arguments' => array(FormBuilder::PERM_EDIT_FORMS),
    'type' => MENU_CALLBACK,
  );
  $items['admin/content/xml/form/%/delete'] = array(
    'title' => 'Delete Form',
    'description' => 'Delete a Form.',
    'file' => 'Delete.inc',
    'file path' => drupal_get_path('module', 'xml_form_builder'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('xml_form_builder_delete', 4),
    'access arguments' => array(FormBuilder::PERM_DELETE_FORMS),
    'type' => MENU_CALLBACK,
  );
  $items['admin/content/xml/form/ahah/controls'] = array(
    'title' => 'Advanced Form Contols',
    'description' => 'Returns the advanced controls for a given form element type.',
    'file' => 'Edit.inc',
    'file path' => drupal_get_path('module', 'xml_form_builder'),
    'page callback' => 'xml_form_builder_ahah_controls',
    'access arguments' => array(FormBuilder::PERM_EDIT_FORMS),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_theme. Register themes.
 *
 * @return array
 */
function xml_form_builder_theme() {
  return array(
    'edit_form_page' => array(
      'arguments' => array('element'),
      'template' => 'Edit',
      'file' => 'Edit.inc'
    ),
  );
}

/**
 * Implements hook_perm. Register permissions.
 * 
 * @return array
 */
function xml_form_builder_perm() {
  module_load_include('inc', 'xml_form_builder', 'FormBuilder');
  return array(
    FormBuilder::PERM_LIST_FORMS,
    FormBuilder::PERM_CREATE_FORMS,
    FormBuilder::PERM_EDIT_FORMS,
    FormBuilder::PERM_DELETE_FORMS,
  );
}

/**
 *
 * @param string $form_name 
 */
function xml_form_builder_export($form_name) {
  module_load_include('inc', 'xml_form_builder', 'FormBuilder');
  FormBuilder::Export($form_name);
  exit();
}