<?php
/**
 * @file
 * Module file for the test solution pack.
 */

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_test_cm_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_test_cm');
  // Test Content Model.
  $test_content_model = $connection->repository->constructObject('islandora:testCModel');
  $test_content_model->owner = 'fedoraAdmin';
  $test_content_model->label = 'Islandora Test Content Model';
  $test_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $test_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_test_cm_ds_composite_model.xml", FALSE);
  $test_content_model->ingestDatastream($datastream);
  // Test Collection.
  $test_collection = $connection->repository->constructObject('islandora:sp_test_collection');
  $test_collection->owner = 'fedoraAdmin';
  $test_collection->label = 'Test Collection';
  $test_collection->models = 'islandora:collectionCModel';
  $test_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection Policy Datastream.
  $datastream = $test_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_test_cm_collection_policy.xml", FALSE);
  $test_collection->ingestDatastream($datastream);
  // TN Datastream.
  $datastream = $test_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $test_collection->ingestDatastream($datastream);
  return array(
    'islandora_test_cm' => array(
      'title' => 'Islandora Test',
      'objects' => array(
        $test_content_model,
        $test_collection,
      ),
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_test_cm_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_test_cm');
  return array(
    'Test Solution Pack MODS Form' => array(
      'form_file' => "$module_path/xml/islandora_test_cm_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_test_cm_islandora_testCModel_islandora_ingest_steps() {
  return array(
    'islandora_test_cm_file_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_test_cm_upload_form',
      'module' => 'islandora_test_cm',
      'file' => 'includes/test_cm_upload.form.inc',
    ),
  );
}

/**
 * Implements hook_islandora_content_model_forms_form_associations().
 */
function islandora_test_cm_islandora_content_model_forms_form_associations() {
  return array(
    'islandora_test_cm_mods_form' => array(
      'content_model' => 'islandora:testCModel',
      'form_name' => 'Test Solution Pack MODS Form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}