<?php

// $Id$

/**
 * @file
 *
 */
module_load_include('inc', 'xml_form_api', 'XMLForm');

/**
 * Register classes for FormProperties.
 * 
 * @return array
 */
function xml_form_api_objectify_properties() {
  $properties['#actions'] = array(
    'type' => 'inc',
    'module' => 'xml_form_api',
    'name' => 'Actions',
    'class' => 'Actions'
  );
  return $properties;
}

//----------------------------------------------------------------------------------------------------------------------
// Test Code
//----------------------------------------------------------------------------------------------------------------------

/**
 * Implementation of Hook Menu.
 *
 * @return array
 */
function xml_form_api_menu() {
  $items['test'] = array(
    'title' => 'Test',
    'description' => 'test',
    'page callback' => 'xml_form_api_test',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Helper test function
 * @return string
 */
function getTestDefinition() {
  $document = new DOMDocument();
  $document->load(drupal_get_path('module', 'xml_form_api') . '/tests/data/definitions/fgdc.xml');
  return $document->saveXML();
}

/**
 * Helper test function
 * @return string
 */
function getTestDocument() {
  $document = new DOMDocument();
  $document->load(drupal_get_path('module', 'xml_form_api') . '/tests/data/documents/fgdc.xml');
  return $document->saveXML();
}

/**
 * 
 */
function xml_form_api_test() {
  return drupal_get_form('xml_form');
}

/**
 *
 * @param type $form_state
 * @return type 
 */
function xml_form(&$form_state) {
  $xml_form = new XMLForm($form_state);
  if (!$xml_form->isInitialized()) { // Was initialized from storage.
    module_load_include('inc', 'xml_form_api', 'XMLFormDefinition');
    module_load_include('inc', 'xml_form_api', 'XMLDocument');
    $xml = getTestDefinition();
    $form = XMLFormDefinition::GetDrupalForm($xml);
    $properties = XMLFormDefinition::GetFormProperties($xml);
    $properties = $properties['document'];
    $test = getTestDocument();
    $document = new XMLDocument($properties['root'], $properties['namespaces'], $properties['schema'], $test);
    $xml_form->initialize($form, $document);
  }
  $output = $xml_form->toArray();
  return $output;
}

function xml_form_validate($form, &$form_state) {
  $xml_form = new XMLForm($form_state);
  $xml_form->validate($form, $form_state);
}

function xml_form_submit($form, &$form_state) {
  $xml_form = new XMLForm($form_state);
  $doc = $xml_form->submit($form, $form_state);
  $document = $doc->document;
  dom_document_pretty_print($document);
  exit();
}